export const navLinks = [
  { name: 'My Trips', href: '/traveler/trips' },
  { name: 'Globe', href: '/traveler/globe' },
];

export const tripCategories = [
  'Adventure',
  'Beach',
  'City Break',
  'Cultural',
  'Cruise',
  'Family',
  'Food & Culinary',
  'Hiking & Trekking',
  'Historical',
  'Honeymoon',
  'Luxury',
  'Nature & Wildlife',
  'Photography',
  'Relaxation',
  'Road Trip',
  'Romantic',
  'Safari',
  'Shopping',
  'Skiing & Snowboarding',
  'Solo Travel',
  'Spiritual & Wellness',
  'Sports & Activities',
  'Volunteer',
  'Weekend Getaway',
];
